### ISSUE TITLE
Location of example data

### ISSUE THREAD

**Issue by vtcloud** [willastro/ENIIGMA-code#2]
Hi,
I am trying to run your example for the continuum fit as taken from the documentation. However, there is a problem with the execution. The problem is in your file ENIIGMA/Continuum/Fit.py. On line 218 of the current version, you determine the current working directory and you are then assuming that the data file is in the current working directory. However, if this is not the case, the execution fails with an error message. In order to make it work safer, you should extract the directory DIR from the file name by searching for the last '/' and operate from there. Now the data file can be anywhere and the files you want to create will end up in an existing directory.

vtcloud

**Comment by willastro** [comment]
Hi,
thanks for running the code and spotting this problem. I only use DIR to extract the characters after the last slash. So far I never had any problem, although always calling the input file from a directory other than the current one. But after you point this out I decided to investigate and figured out that in a few cases, the code crashes. So I have now replaced the searching method and the problem is solved.
